server:
  port: 8081
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git: 
          uri: file://home/x/Documents/workspaces/ms/git/microservices-sample-application/microservices-sample-application/app-config
  security:
    user:
      name: configUser
      password: configPassword
      roles: SYSTEM
  
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8082/eureka/

