server:
  port: 8082
spring:
  application:
    name: discovery
  cloud:
    config:
      :fail-fast: true
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
     
eureka: 
  client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
        defaultZone: http://discUser:discPassword@localhost:8082/eureka/
  instance: 
    hostname: localhost
    healthcheck:
      enabled: true  