server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    config:
      :fail-fast: true
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  sleuth: 
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)

management:
  security:
    sessions: always
     
eureka: 
  client:
      region: default
      registryFetchIntervalSeconds: 5
      serviceUrl:
        defaultZone: http://discUser:discPassword@localhost:8082/eureka/
  instance: 
    hostname: localhost
    
zuul:
  routes:
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
    sample-service:
      path: /sample-service/**
      sensitive-headers: Set-Cookie,Authorization
    
hystrix:
  command:  
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    sample-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
 
            
sample-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxConnectionsPerHost: 100
 
#logging.level.org.springframework.web.=debug
#logging.level.org.springframework.security=debug
#logging.level.org.springframework.cloud.netflix.zuul=debug
#logging.level.org.springframework.session=debug

