spring:
  application:
    name: sample-service
  cloud:
    config:
      :fail-fast: true
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  sleuth: 
    sampler:
      probability: 1.0
    web:
      skipPattern: (^cleanup.*)

management:
  security:
    sessions: never

eureka: 
  client:
      region: default
      registryFetchIntervalSeconds: 5
    



#logging.level.org.springframework.web.=debug
#logging.level.org.springframework.security=trace
#logging.level.org.springframework.session=trace
#logging.level.org.springframework=trace
